# Generated by Django 4.2.1 on 2024-05-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0006_rename_created_at_carritocompra_creado_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='producto',
        ),
        migrations.DeleteModel(
            name='CarritoCompra',
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
