# Generated by Django 4.2.1 on 2024-06-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0008_orden_ordenitem_direccionenvio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contraseña',
        ),
    ]
