# Generated by Django 4.2.1 on 2024-06-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0009_remove_cliente_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
    ]
