# Generated by Django 4.2.1 on 2024-06-07 23:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0010_remove_cliente_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='id',
        ),
        migrations.AlterField(
            model_name='orden',
            name='transaccion_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
