# Generated by Django 4.2.1 on 2024-06-09 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0011_remove_orden_id_alter_orden_transaccion_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=4000)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
