# Generated by Django 4.2.1 on 2024-06-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0012_opion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opion',
            new_name='Opinion',
        ),
    ]
