# Generated by Django 4.2.1 on 2024-06-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0015_alter_direccionenvio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionenvio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
