# Generated by Django 4.2.1 on 2024-06-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0018_direccionenvio_recibido'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizado',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
