# Generated by Django 4.2.1 on 2024-06-13 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0020_calificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
