# Generated by Django 4.2.1 on 2024-06-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0026_rating_delete_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.TextField(),
        ),
    ]
